name 'rails-test-chef'
maintainer 'Oriol Francès'
maintainer_email 'oriolfa@gmail.com'
license 'all_rights'
description 'Installs/Configures rails-test-chef'
long_description 'Installs/Configures rails-test-chef'
version '0.1.0'
depends 'apt', '~> 2.7.0'
depends 'build-essential', '~> 2.2.3'
depends 'user'
depends 'nginx', '~> 2.7.6'
depends 'database'
depends 'mysql'
depends 'mysql2_chef_gem'
depends 'rbenv'
depends 'nodejs'
depends "logrotate"
depends "sudo"
depends 'ssh_authorized_keys'
